name: Automatically create Pull Request

on:
  push:
    branches-ignore:
    - "main"  

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""                                 
        destination_branch: "main"                     
        pr_title: "Belegabgabe: ${{ github.ref }}"
        pr_template: ".github/PULL_REQUEST_TEMPLATE.md"  
        pr_reviewer: "htwb-steven"                         
        pr_label: "Belegabgabe, ${{ github.ref }}"                               
        pr_draft: true                                    # Creates pull request as draft
        pr_allow_empty: true                              # Creates pull request even if there are no changes
        github_token: ${{ secrets.GITHUB_TOKEN }}