name: runmerunner clean, build, test & package 

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    # define os, versions, ...
    strategy:
      matrix:
        os: [ubuntu-18.04]
        java: [11]
    # run on os ...
    runs-on: ${{ matrix.os }}
    # all build steps
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        java-package: jdk 
        architecture: x64 
    - name: runmerunner clean, build, test & package
      run: mvn -pl runmerunner clean package
    - name: copy runmerunner test classes
      run: ./runmerunner/TestClasses/htwb/*.java ./runmerunner/src/main/java/htwb
    - name: Run tests
      run: |
        jarpath=$(ls ./runmerunner/target/runmerunner-*.jar)
        jarname=$(basename $jarpath)
        echo $jarname
        java -jar target/$jarname
        java -jar target/$jarname dieseklassegibtesnicht
        java -jar target/$jarname java.io.Closeable
        java -jar target/$jarname htwb.ClassNoDefConstr
        java -jar target/$jarname htwb.ClassWithRunMes
