name: songsWSa clean, build, test, package & run scripts

on:
  pull_request:
    branches:
      - main
      - master
      
    
jobs:
  build:
    # define os, versions, ...
    strategy:
      matrix:
        os: [ubuntu-18.04]
        java: [11]
    # run on os ...
    runs-on: ${{ matrix.os }}
    # tomcat service
    services:
      container:
        image: tomcat:9.0.37-jdk11
        ports:
          - 8080:8080
          - 8443:8443
        options:
          --name tomcat
    # all build steps
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          architecture: x64
      - name: songsWS clean, build, test & package
        run: mvn -pl songsWS clean package
      - name: add self signed certificate and settings
        run: |
          docker cp ./songsWS/ssl/.keystore tomcat:/etc/ssl/certs/
          docker cp ./songsWS/ssl/server.xml tomcat:/usr/local/tomcat/conf/
          docker stop tomcat
          docker start tomcat
          docker exec tomcat ls /etc/ssl/certs/
          docker exec tomcat ls /usr/local/tomcat/
      - name: move .war to Tomcat container
        run: |
          docker cp ./songsWS/target/songsWS-*.war tomcat:/usr/local/tomcat/webapps
          docker exec tomcat ls /usr/local/tomcat/webapps
          sleep 180
      - name: run TestScripts
        run: |
          servletfile=$(ls ./songsWS/target/songsWS-*.war)
          servletname=$(basename $servletfile .war)
          echo $servletname
          sh ./songsWS/scripts/songsWSPostTester.sh $servletname
          sh ./songsWS/scripts/songsWSTester.sh $servletname
